package com.accenture;

public class MainDemo {

    String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public static void main(String[] args) {
        System.out.println("Hello Pod 1!");
        //ctrl + alt + L
        //        ctrl + /
        /*
         * ctrl + alt + /
         * alt + insert = autogenerated code display
         * shift + tab = unindent line
         * ctrl +z and ctrl + y = undo, redo
         * alt + shift + leftclick = select multiple code at the same time
         * */


    }


}
